name: travel_app
description: Flutter challange 2 travel app https:&#x2F;&#x2F;dribbble.com&#x2F;shots&#x2F;5741425-Travel-App&#x2F;attachments

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  community_material_icon:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
        - asset: assets/fonts/Raleway/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway/Raleway-ExtraLightItalic.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
        - asset: assets/fonts/Raleway/Raleway-LightItalic.ttf
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway/Raleway-MediumItalic.ttf
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway/Raleway-ThinItalic.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
